apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-helloworld 
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd-demo/python-manifests
    repoURL: https://github.com/Oyindamola-victor/python-helloworld/blob/main/ 
    targetRevision: HEAD
  syncPolicy: {}
